# 使用 OpenJDK 17 作为基础镜像
FROM openjdk:17-jdk-slim

# 设置工作目录
WORKDIR /app

# 将 当前目录 的 target 目录复制到 Docker 镜像中
COPY /UserSystemJdk17/target/*.jar /app/UserSystemJdk17.jar

# 暴露应用程序的端口（如果需要的话）
EXPOSE 8080

# 定义容器启动时执行的命令
CMD ["java", "-jar", "UserSystemJdk17.jar"]