spring:
  output:
    ansi:
      enabled: detect
  profiles:
    active: dev
  mvc:
    path match:
      matching-strategy: ant_path_matcher
server:
  port: 8090
  tomcat:
    max-http-header-size: 16384

wechat:
  appid: wx574d9b296a054784
  appsecret: 96365105c2d3a12290431b862083364a
  token:
    url: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=${wechat.appid}&secret=${wechat.appsecret}
  send:
    message: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=
    templateId: YPtS4XTIBS7Fsd1jap8Uh5G_fV5LfOY3Ty5h5yF6DR8
    toUser: ooQLO6VnYwG0pfHM6InHyr1VjgdM # opc9-6dau3sPq0cI9YKRbwci-eYM opc9-6a01s7z46uYoh8VP1RV-MBw
  create:
    menu: https://api.weixin.qq.com/cgi-bin/menu/create?access_token=
  upload:
    file: https://api.weixin.qq.com/cgi-bin/material/add_material?access_token=
  get:
    mediaList: https://api.weixin.qq.com/cgi-bin/material/batchget_material?access_token=

  access:
    token: 6dau3sPq0cI9YKRbwci
  imge: wNFKAvg_badI-zsrsDgpQKhYaYoi-EHElZFuAv-DRO4u3N9lCb3J1ted7fPo105t
  video: wNFKAvg_badI-zsrsDgpQP_OwziDXgdbwS_EzObC4GMG53l1sjzVC_3Xxdv9Qc-y

hf:
  location: 113.039992,28.241713
  weather:
    url: https://devapi.qweather.com/v7/weather/now?location=${hf.location}&key=${hf.key}
  key: 1b2ea129968d4573a566ecb8874a2662

holiday:
  url: http://timor.tech/api/holiday/year/
