# MyBatis Plus 配置
mybatis-plus:
  # 映射器XML文件的位置
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  # 全局配置
  global-config:
    # 数据库配置
    db-config:
      # 表示逻辑删除的值
      logic-delete-value: 1
      # 表示逻辑未删除的值
      logic-not-delete-value: 0
  # MyBatis 配置
  configuration:
    # 启用从下划线到驼峰的映射
    map-underscore-to-camel-case: true
  # 配置位置
  config-location:
    # 日志实现（当前设置为无日志）
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

# MySQL 配置
mysql:
  # MySQL 数据源
  datasource: 120.24.254.250:3307
  # 数据库名称
  db-name: renrendb
  # 数据库用户名
  username: root
  # 数据库密码
  password: zpj520996

# Spring 配置
spring:
  # MySQL 配置
  datasource:
    # MySQL 数据库的JDBC URL
    url: jdbc:p6spy:mysql://${mysql.datasource}/${mysql.db-name}?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Hongkong
    # 数据库用户名
    username: ${mysql.username}
    # 数据库密码
    password: ${mysql.password}
    # 数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    # MySQL 数据库的驱动类名
    driverClassName: com.mysql.cj.jdbc.Driver
  # 邮件配置
  mail:
    # SMTP 主机
    host: smtp.163.com
    # 邮件主题
    subject: 验证码邮件
    # 邮件协议
    protocol: smtp
    # 发送邮件的邮箱地址
    username: zhangpengju_syy@163.com
    # 邮箱账户的密码
    password: TRBLMAJQTEPKLHCE
    # 测试连接
    test-connection: true
    # 邮件的默认编码
    default-encoding: utf-8
    # 邮件属性
    properties:
      # 启用SMTP认证
      mail.smtp.auth: true
      # 启用STARTTLS
      mail.smtp.starttls.enable: true
      # 需要STARTTLS
      mail.smtp.starttls.required: true
      # SMTP套接字工厂端口
      mail.smtp.socketFactory.port: 465
      # SMTP套接字工厂类
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      # SMTP套接字工厂回退
      mail.smtp.socketFactory.fallback: false
    # SMTP端口
    port: 465
  # Redis 配置
  data:
    redis:
      # Redis 数据库
      database: 0
      # Redis 主机
      host: 120.24.254.250
      # Redis 端口
      port: 36379
      # Redis 超时
      timeout: 1000
      # Redis 密码
      password:

# 日志配置
logging:
  # cn.percent 包的日志级别
  level:
    cn.percent: debug

# JWT 配置
jwt:
  # 访问令牌配置
  access:
    token:
      # 访问令牌的过期时间
      expiration: 10
  # 刷新令牌配置
  refresh:
    token:
      # 刷新令牌的过期时间
      expiration: 30


# RSA 配置
ras:
  # 公钥
  public:
    key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDVsHP0tU9VUFyZiUt2dF7d3nYS+Q7RT5Bg8toS6XyiqNRcFD/2T+FJmA3tRy4KMxRPn7WrECcDlZQRXE8onJhz5WuPxXz1YFFt19vnI+eniXXWwfunSFICa1g/5f81YH+b1z/wqyM/DQYpoL+yfNwae0BqUhU71SmlTJ7yM68nxQIDAQAB
  # 私钥
  private:
    key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBANWwc/S1T1VQXJmJS3Z0Xt3edhL5DtFPkGDy2hLpfKKo1FwUP/ZP4UmYDe1HLgozFE+ftasQJwOVlBFcTyicmHPla4/FfPVgUW3X2+cj56eJddbB+6dIUgJrWD/l/zVgf5vXP/CrIz8NBimgv7J83Bp7QGpSFTvVKaVMnvIzryfFAgMBAAECgYBSlLmLNVJuZvsSPtPR+FD9L060MFoAm93xCYkrS95lwhcnao/5cY9f8IpZS2vId0r/Jnp/nGNnaDPrrZ/N0w667nkrklyFMgOcHftq6fiIaM+XF7AwmSAw5fB211plF/6nENr/+WdnHwkKIY0VA4NGr0IYo8YB7w5cLtvoY1yYNQJBAO8T1Vh5hpvulTqTfRYfKRsTNG+CegdpUFDtWnwkqghwdBHhsWEj1SFPHR/3BviM5KM1qp39PvBOP1vJqwRoMNsCQQDk0JOWGcPo5b2e397V15dQJyP9/+u7TmuXBdIJ6H0RXi1tGzQ3iX2v6mzQcPLpiTeJYBHZzzb5Akz46IfpiJvfAkAIW4YiwKTPAKkg0hUWV+KE+sfjegkwByNyoMl/+3wiLWQxV9VukuUZc/2Np4IL4EkB15duTHMNzX5zg/pBfi7vAkEArHJFyKpCbBQ5hLNUTfXdpBrblWJ7Vv8TNw677Zu6JozDz6bhA7orb5lNyQpXCIrRwEcXLQBufdyuBim5xNegIQJAWWfmaGE0PPQx1sUlQXJ+ghx+9CIkoLq6YJHd29/2jzaziItvaAwbBNekzgaMXE/CzzYuFYh2qmPl2A8vISiifA==

# 登录URL
login:
  url: http://101.43.142.189:9091/system/user/qrCodeScan

# WebSocket 配置
webSocketConfig:
  # WebSocket URL
  ws: ws://101.43.142.189:9091/webSocket/