#在yml文件中写入当前的配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  config-location:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 可以打印出其中sql语句的日志
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
mysql:
  datasource: 120.24.254.250:3307
  db-name: renrendb
  username: root
  password: zpj520996

spring:
  # MySQL 配置
  datasource:
    url: jdbc:mysql://${mysql.datasource}/${mysql.db-name}?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Hongkong
    username: ${mysql.username}
    password: ${mysql.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    subject: 验证码邮件
    #服务协议
    protocol: smtp
    username: zhangpengju_syy@163.com #你注册的网易邮箱
    password: TRBLMAJQTEPKLHCE #你获取到的授权码
    test-connection: true
    default-encoding: utf-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
    port: 465
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
  messages:
    basename: i18n/messages
  main:
    allow-circular-references: true
  data:
    redis:
      database: 0
      host: 120.24.254.250
      port: 36379
      timeout: 1000
      password:
#配置日志
logging:
  level:
    cn.percent: debug

jwt:
  access:
    token:
      expiration: 10 # token存在时间
  refresh:
    token:
      expiration: 30 # 刷新token存在时间

swagger:
  enable: true
  base:
    package: cn.percent.system
  contact:
    email: 2712450214@qq.com
    name: pengju.zhang
    url:
  description: 登录地址请访问 http://101.43.142.189/login
  title: UserSystem
  url: ''
  version: 1.0

ras:
  public:
    key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDVsHP0tU9VUFyZiUt2dF7d3nYS+Q7RT5Bg8toS6XyiqNRcFD/2T+FJmA3tRy4KMxRPn7WrECcDlZQRXE8onJhz5WuPxXz1YFFt19vnI+eniXXWwfunSFICa1g/5f81YH+b1z/wqyM/DQYpoL+yfNwae0BqUhU71SmlTJ7yM68nxQIDAQAB
  private:
    key: MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBANWwc/S1T1VQXJmJS3Z0Xt3edhL5DtFPkGDy2hLpfKKo1FwUP/ZP4UmYDe1HLgozFE+ftasQJwOVlBFcTyicmHPla4/FfPVgUW3X2+cj56eJddbB+6dIUgJrWD/l/zVgf5vXP/CrIz8NBimgv7J83Bp7QGpSFTvVKaVMnvIzryfFAgMBAAECgYBSlLmLNVJuZvsSPtPR+FD9L060MFoAm93xCYkrS95lwhcnao/5cY9f8IpZS2vId0r/Jnp/nGNnaDPrrZ/N0w667nkrklyFMgOcHftq6fiIaM+XF7AwmSAw5fB211plF/6nENr/+WdnHwkKIY0VA4NGr0IYo8YB7w5cLtvoY1yYNQJBAO8T1Vh5hpvulTqTfRYfKRsTNG+CegdpUFDtWnwkqghwdBHhsWEj1SFPHR/3BviM5KM1qp39PvBOP1vJqwRoMNsCQQDk0JOWGcPo5b2e397V15dQJyP9/+u7TmuXBdIJ6H0RXi1tGzQ3iX2v6mzQcPLpiTeJYBHZzzb5Akz46IfpiJvfAkAIW4YiwKTPAKkg0hUWV+KE+sfjegkwByNyoMl/+3wiLWQxV9VukuUZc/2Np4IL4EkB15duTHMNzX5zg/pBfi7vAkEArHJFyKpCbBQ5hLNUTfXdpBrblWJ7Vv8TNw677Zu6JozDz6bhA7orb5lNyQpXCIrRwEcXLQBufdyuBim5xNegIQJAWWfmaGE0PPQx1sUlQXJ+ghx+9CIkoLq6YJHd29/2jzaziItvaAwbBNekzgaMXE/CzzYuFYh2qmPl2A8vISiifA==

login:
  url: http://101.43.142.189:9091/system/user/qrCodeScan

webSocketConfig:
  ws: ws://101.43.142.189:9091/webSocket/



