# .github/workflows/java-ci-cd.yml

name: Java CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.

      - name: Build with Maven
        run: mvn -B clean package

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: /UserSystemJdk17
          file: Dockerfile
          push: true
          tags: |
            ying520zhang/usersystem:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push ying520zhang/usersystem:latest
