name: Docker Image CI Test

on:
  push:
    branches: [ "main" ]  # Change this to your test branch
  pull_request:
    branches: [ "main" ]  # Change this to your test branch

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package
      - name: Build the Docker image
        run: |
          TIMESTAMP=$(date +%s)
          docker build . --file ./DockerFile --tag ying520zhang/usersystem:$TIMESTAMP
          echo "DOCKER_IMAGE_TAG=$TIMESTAMP" >> $GITHUB_ENV
      - name: Push the Docker image
        run: |
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker push ying520zhang/usersystem:${{ env.DOCKER_IMAGE_TAG }}

      - name: 安装阿里云 CLI
        run: |
          curl -o install.sh https://raw.githubusercontent.com/aliyun/aliyun-cli/master/install.sh || exit 1
          bash install.sh || exit 1
          echo "export PATH=$PATH:/usr/local/bin" >> ~/.bashrc
          source ~/.bashrc
          rm install.sh

      - name: 配置阿里云 CLI
        run: |
          source ~/.bashrc
          aliyun configure --profile default \
            --access-key-id ${{ secrets.ALIYUN_ACCESS_KEY_ID }} \
            --access-key-secret ${{ secrets.ALIYUN_ACCESS_KEY_SECRET }}

      - name: 连接到阿里云 ECS
        run: |
          ecs login --region-id ${{ secrets.ALIYUN_REGION_ID }} \
            --instance-id ${{ secrets.ALIYUN_INSTANCE_ID }}

      - name: 拉取镜像
        run: docker pullying520zhang/usersystem:${{ env.DOCKER_IMAGE_TAG }}